In [2]:
from datasets import load_dataset
from src.common.constants import Constants as consts

first_4_rows = [r for _, r in zip(range(4),load_dataset(consts.mls_eng_ds_path, split="dev", streaming=True))]

Resolving data files:   0%|          | 0/1416 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/1416 [00:00<?, ?it/s]

In [ ]:
first_row = first_4_rows[0]
# print(first_row['audio'])
print("First row contents:")
for key, value in first_row.items():
    print(f"{key}: {value}")

audio: {'path': '10214_10108_000000.opus', 'array': array([ 3.87812361e-05, -9.20808670e-05, -2.10028462e-04, ...,
        1.81236261e-04,  3.54383665e-05, -1.41409037e-04], shape=(198400,)), 'sampling_rate': 16000}
original_path: http://www.archive.org/download/birdsvol5feb1899_1510_librivox/birdsandallnaturefeb1899_14_various_64kb.mp3
begin_time: 32.46
end_time: 44.86
transcript: but the owl is not a burglar he is the friend of man there is no other bird that does the farmer so much good as the owl the owl comes out in the dark to get the small animals that are out at that time stealing things from the farmer
audio_duration: 12.4
speaker_id: 10214
book_id: 10108


In [10]:
first_4_rows_spoof = [r for _,r in zip(range(4), load_dataset(consts.audeter_ds_path, consts.tts_and_vocoders_configs[0], split="dev", streaming=True))]

In [11]:
first_row_spoof = first_4_rows_spoof[0]
for key, value in first_row_spoof.items():
    print(f"{key}: {value}")

wav: {'path': 'dev/1055_0.wav', 'array': array([0.01663524, 0.01829608, 0.02186299, ..., 0.00131217, 0.00148168,
       0.00130851], shape=(315840,)), 'sampling_rate': 24000}
__key__: dev/1055_0
__url__: hf://datasets/wqz995/AUDETER@87eef4ac6eb8a6c819c3b230d6fcc176482d3a22/mls/tts/bark/dev/v0.tar


In [16]:
test_dict = {"A": 1, "B": 2}
print("Before modify")
for k in test_dict.keys():
    print(k)
    
print("After modify")
test_dict["C"] = test_dict.pop("A")
for k in test_dict.keys():
    print(k)

Before modify
A
B
After modify
B
C


In [9]:
import pandas as pd
test_dict_2 = {"A" : pd.Series([1, 2, 3]), "B": pd.Series([1,2])}
df = pd.DataFrame(test_dict_2)
df = df.fillna(-1).astype(int)
df.head()

A  B
0  1  1
1  2  2
2  3 -1

In [4]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1, 2])
print(np.hstack([a, b]))

[1 2 3 1 2]


In [8]:
import pandas as pd

a = pd.DataFrame({"a": [1, 2, 3, 4, 5, 6], "b": [2, 8, 3, 10, 20, 1]})

print(a['a'].isin(a['b']))
print(a['b'].isin(a['a']))

0     True
1     True
2     True
3    False
4    False
5    False
Name: a, dtype: bool
0     True
1    False
2     True
3    False
4    False
5     True
Name: b, dtype: bool


In [5]:
import numpy as np

LABELS = ["bonafide", "spoof"]

print([str(np.random.choice(LABELS, p=[0.7, 0.3])) for _ in range(20)])

['bonafide', 'bonafide', 'spoof', 'bonafide', 'bonafide', 'bonafide', 'bonafide', 'bonafide', 'bonafide', 'spoof', 'spoof', 'spoof', 'bonafide', 'spoof', 'spoof', 'bonafide', 'bonafide', 'bonafide', 'bonafide', 'bonafide']


In [13]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(np.concat([a, b], axis=0))
print(np.vstack([a, b]))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [16]:
import pandas as pd
data = {'col1': [1, 2, 3, 4],
        'col2': [5, 6, 7, 8]}
data_1 = {
    'col1': [9, 10, 11, 12],
    'col2': [11, 12, 13, 14]
}

df, df1 = pd.DataFrame(data), pd.DataFrame(data_1)
combined_df = pd.concat([df, df1], ignore_index=True)
print(combined_df)

   col1  col2
0     1     5
1     2     6
2     3     7
3     4     8
4     9    11
5    10    12
6    11    13
7    12    14


In [20]:
from imblearn.under_sampling import RandomUnderSampler
import pandas as pd 

df = pd.DataFrame(
    {'col1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
     "target": [0, 0, 0, 1, 0, 0, 0, 1, 0, 0]
    })

ros = RandomUnderSampler(sampling_strategy=0.5, random_state=42)
df_under, _ = ros.fit_resample(df, df['target'])

df_under

col1  target
1     2       0
6     7       0
0     1       0
9    10       0
3     4       1
7     8       1

In [50]:
def _calculate_target_length_for_oversampling(metadata: pd.DataFrame, target_col: str, ratio: float):
    bonafide_count = np.sum(metadata[target_col] == 0)
    spoof_count = np.sum(metadata[target_col] == 1)
    target_bonafide_count = int(spoof_count * ratio / (1 - ratio))
    target_length = spoof_count + target_bonafide_count
    return target_length
target_length = _calculate_target_length_for_oversampling(
    metadata=df,
    target_col="target",
    ratio=0.8
)
print("Target length for oversampling:", target_length)

Target length for oversampling: 10


In [58]:
from imblearn.over_sampling import RandomOverSampler

ros1 = RandomOverSampler(sampling_strategy=0.8, random_state=42)
df_over, _ = ros1.fit_resample(df, df['target'])
print(df_over.shape)
df_over

(14, 2)


col1  target
0      1       0
1      2       0
2      3       0
3      4       1
4      5       0
5      6       0
6      7       0
7      8       1
8      9       0
9     10       0
10     4       1
11     8       1
12     4       1
13     4       1

In [55]:
from pathlib import Path
from src.common.constants import Constants as consts
data_dir = consts.data_dir / "dupa.csv"
print(data_dir)
print(data_dir.stem)

/Users/mikolajkarapka/Projects/audio-deepfake-detection-uwr/data/dupa.csv
dupa


In [62]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    {'col1': [1, 2, 3, 4],
     "target": [0, 0, 0, 1]
    })

example_embeddings = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9],
    [1.0, 1.1, 1.2]
])

sampled_df = df.sample(n=10, replace=True, random_state=42)
sampled_df


col1  target
2     3       0
3     4       1
0     1       0
2     3       0
2     3       0
3     4       1
0     1       0
0     1       0
2     3       0
1     2       0

In [64]:
example_embeddings_sampled = example_embeddings[sampled_df.index]
print(example_embeddings.shape)
print(example_embeddings_sampled.shape)

(4, 3)
(10, 3)


In [2]:
import pandas as pd
from pathlib import Path
from src.common.constants import Constants as consts
embd_path = consts.collected_data_dir / "wavlm_extracted.npy"
metadata_path = consts.collected_data_dir / "wavlm_extracted.csv"

metadata = pd.read_csv(metadata_path)
# embeddings = np.load(embd_path)

In [3]:
print(metadata.shape)
# print(embeddings.shape)


(268964, 4)


In [ ]:
from src.preprocessing.data_balancers.oversample_real_balancer import OversampleRealBalancer
from src.preprocessing.feature_loader import FeatureLoader

balancer = OversampleRealBalancer(real_to_spoof_ratio=0.5)
feature_loader = FeatureLoader(file_name="wavlm_extracted")

balanced_meta = balancer.resample(metadata)


In [5]:
print(feature_loader.emb_path)

/Users/mikolajkarapka/Projects/audio-deepfake-detection-uwr/data/collected_data/wavlm_extracted.npy


In [6]:
new_emb = feature_loader.load_embeddings_from_metadata(balanced_meta)

In [7]:
print(new_emb.shape)

(324678, 768)
