# Test 2

## Attempt to train UMAP on frac_train set and transform frac_all embeddings, then cluster and plot

### Pseudo-code
1. X_train = umap.fit_transform(train_split)
2. clusterizer.fit(X_train)
3. X_all = umap.transform(all)
4. clusterizer.predict(all)

In [ ]:
plt.title('t-SNE Visualization of Sampled 10% Dataset')

In [ ]:
from src.models.mlp_classifier import MLPClassifier
from src.preprocessing.io.feature_loader import FeatureLoader
from src.common.constants import Constants as consts
feature_loader = FeatureLoader(file_name=consts.feature_extracted, feat_suffix="fft")

train_meta, train_embeddings = feature_loader.load_data_split(split_name="train")
print(train_meta.shape, train_embeddings.shape)


(788680, 10) (788680, 1026)


In [6]:
sampled_train_meta, sampled_train_emb = feature_loader.sample_fraction_metadata_and_embeddings(train_meta, train_embeddings, fraction=0.4)
print(sampled_train_meta.shape, sampled_train_emb.shape)

(315472, 10) (315472, 1026)


In [ ]:
dev_meta, dev_embeddings = feature_loader.load_data_split(split_name="dev")
print(dev_meta.shape, dev_embeddings.shape)
sampled_dev_meta, sampled_dev_emb = feature_loader.sample_fraction_metadata_and_embeddings(dev_meta, dev_embeddings, fraction=0.2)
print(sampled_dev_meta.shape, sampled_dev_emb.shape)

(158372, 10) (158372, 1026)
(31674, 10) (31674, 1026)


In [8]:
# Test on FFT embeddings without cluster ids 10%
clf = MLPClassifier()
clf.optuna_fit(
    n_trials=50,
    X_train=sampled_train_emb,
    y_train=sampled_train_meta['target'].to_numpy(),
    X_dev=sampled_dev_emb,
    y_dev=sampled_dev_meta['target'].to_numpy(),
)
print("Best trial value (lowest loss):", clf.get_best_value())

2026-01-23 02:59:17 | INFO     | audio_deepfake.MLPClassifier | Initialized model: MLPClassifier
2026-01-23 02:59:17 | INFO     | audio_deepfake.MLPClassifier | Using device: mps


(array([0., 1.], dtype=float32), array([300799,  14673])) (array([0., 1.], dtype=float32), array([30267,  1407]))


[I 2026-01-23 02:59:23,419] A new study created in memory with name: no-name-daf38abd-f244-46dc-b009-5cd23bce0e27


  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-23 03:02:16,990] Trial 0 finished with value: 0.9525129982668977 and parameters: {'n_layers': 1, 'hidden_size': 256, 'dropout_rate': 0.28040793614793347, 'lr': 0.0018350222373991008, 'weight_decay': 2.8260735950499405e-05, 'epochs': 39, 'batch_size': 256}. Best is trial 0 with value: 0.9525129982668977.
[I 2026-01-23 03:04:14,275] Trial 1 finished with value: 0.921242774566474 and parameters: {'n_layers': 1, 'hidden_size': 384, 'dropout_rate': 0.223125139856039, 'lr': 0.004401635869320636, 'weight_decay': 6.172731782709412e-05, 'epochs': 31, 'batch_size': 512}. Best is trial 0 with value: 0.9525129982668977.
[I 2026-01-23 03:06:19,191] Trial 2 finished with value: 0.8603621730382294 and parameters: {'n_layers': 2, 'hidden_size': 512, 'dropout_rate': 0.3205451005084846, 'lr': 0.0018783590956875087, 'weight_decay': 8.86509188861624e-06, 'epochs': 24, 'batch_size': 256}. Best is trial 0 with value: 0.9525129982668977.
[I 2026-01-23 03:11:02,410] Trial 3 finished with value: 0.9

In [ ]:
# Test on FFT embeddings without cluster ids 10%
clf = MLPClassifier()
clf.optuna_fit(
    n_trials=50,
    X_train=sampled_train_emb,
    y_train=sampled_train_meta['target'].to_numpy(),
    X_dev=sampled_dev_emb,
    y_dev=sampled_dev_meta['target'].to_numpy(),
)
print("Best trial value (lowest loss):", clf.get_best_value())

2026-01-23 02:22:14 | INFO     | audio_deepfake.MLPClassifier | Initialized model: MLPClassifier
2026-01-23 02:22:14 | INFO     | audio_deepfake.MLPClassifier | Using device: mps


(array([0., 1.], dtype=float32), array([75211,  3657])) (array([0., 1.], dtype=float32), array([15117,   720]))


[I 2026-01-23 02:22:14,990] A new study created in memory with name: no-name-5e7705b8-a981-4172-862b-a0cf5f86baae


  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-23 02:23:19,040] Trial 0 finished with value: 0.5201612903225806 and parameters: {'n_layers': 3, 'hidden_size': 384, 'dropout_rate': 0.3629207515664002, 'lr': 0.004295881516068673, 'weight_decay': 0.00023779889479806513, 'epochs': 40, 'batch_size': 256}. Best is trial 0 with value: 0.5201612903225806.
[I 2026-01-23 02:24:16,690] Trial 1 finished with value: 0.7645764576457645 and parameters: {'n_layers': 3, 'hidden_size': 320, 'dropout_rate': 0.21708943799413843, 'lr': 0.0025750516790934417, 'weight_decay': 2.415329850352206e-06, 'epochs': 46, 'batch_size': 512}. Best is trial 1 with value: 0.7645764576457645.
[I 2026-01-23 02:24:51,298] Trial 2 finished with value: 0.325 and parameters: {'n_layers': 3, 'hidden_size': 320, 'dropout_rate': 0.20701845037238484, 'lr': 0.0004524069943088816, 'weight_decay': 2.8516469979738408e-05, 'epochs': 22, 'batch_size': 256}. Best is trial 1 with value: 0.7645764576457645.
[I 2026-01-23 02:25:52,685] Trial 3 finished with value: 0.909992912

In [5]:
# Test on FFT embeddings without cluster ids
clf = MLPClassifier()
clf.optuna_fit(
    n_trials=50,
    X_train=sampled_train_emb,
    y_train=sampled_train_meta['target'].to_numpy(),
    X_dev=sampled_dev_emb,
    y_dev=sampled_dev_meta['target'].to_numpy(),
    train_cluster_id=sampled_train_meta['cluster_id'].to_numpy(),
    dev_cluster_id=sampled_dev_meta['cluster_id'].to_numpy()
)
print("Best trial value (lowest loss):", clf.get_best_value())

2026-01-23 02:35:15 | INFO     | audio_deepfake.MLPClassifier | Initialized model: MLPClassifier
2026-01-23 02:35:15 | INFO     | audio_deepfake.MLPClassifier | Using device: mps


(array([0., 1.], dtype=float32), array([75211,  3657])) (array([0., 1.], dtype=float32), array([15117,   720]))


2026-01-23 02:35:16 | INFO     | audio_deepfake.MLPClassifier | Using cluster_id as additional feature (train clusters: 57, dev clusters: 55)
[I 2026-01-23 02:35:16,226] A new study created in memory with name: no-name-771f648d-fa58-48e3-b95d-7cddb35cebc8


  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-23 02:36:35,996] Trial 0 finished with value: 0.7838006230529595 and parameters: {'n_layers': 3, 'hidden_size': 64, 'dropout_rate': 0.20887529465169044, 'lr': 0.0032022562859970734, 'weight_decay': 0.0003984062861008037, 'epochs': 46, 'batch_size': 256}. Best is trial 0 with value: 0.7838006230529595.
[I 2026-01-23 02:36:48,597] Trial 1 finished with value: 0.6477174849267873 and parameters: {'n_layers': 2, 'hidden_size': 192, 'dropout_rate': 0.18531298678677224, 'lr': 0.00016501644069379779, 'weight_decay': 5.357743389805804e-06, 'epochs': 10, 'batch_size': 512}. Best is trial 0 with value: 0.7838006230529595.
[I 2026-01-23 02:38:09,771] Trial 2 finished with value: 0.8255813953488372 and parameters: {'n_layers': 3, 'hidden_size': 320, 'dropout_rate': 0.3144346281754217, 'lr': 0.0023643504342789026, 'weight_decay': 8.8221556193952e-05, 'epochs': 37, 'batch_size': 128}. Best is trial 2 with value: 0.8255813953488372.
[I 2026-01-23 02:38:44,755] Trial 3 finished with value: 0

In [ ]:
# Test on WavLM embeddings
clf = MLPClassifier()
clf.optuna_fit(
    n_trials=10,
    X_train=sampled_train_emb,
    y_train=sampled_train_meta['target'].to_numpy(),
    X_dev=sampled_dev_emb,
    y_dev=sampled_dev_meta['target'].to_numpy(),
)
print("Best trial value (lowest loss):", clf.get_best_value())

2026-01-23 01:28:32 | INFO     | audio_deepfake.MLPClassifier | Initialized model: MLPClassifier
2026-01-23 01:28:32 | INFO     | audio_deepfake.MLPClassifier | Using device: mps
[I 2026-01-23 01:28:32,964] A new study created in memory with name: no-name-b4f6ead4-924a-492a-a468-ff7deda3a8b0


  0%|          | 0/10 [00:00<?, ?it/s]

[I 2026-01-23 01:28:51,129] Trial 0 finished with value: 0.3201803833145434 and parameters: {'n_layers': 2, 'hidden_size': 256, 'dropout_rate': 0.18749971098064122, 'lr': 0.0008296334866097553, 'weight_decay': 6.494877307523945e-06, 'epochs': 10, 'batch_size': 512}. Best is trial 0 with value: 0.3201803833145434.
[I 2026-01-23 01:29:08,679] Trial 1 finished with value: 0.2475583017739685 and parameters: {'n_layers': 3, 'hidden_size': 128, 'dropout_rate': 0.38604620774425097, 'lr': 0.000156376675288597, 'weight_decay': 1.3361661713367854e-06, 'epochs': 11, 'batch_size': 512}. Best is trial 0 with value: 0.3201803833145434.
[I 2026-01-23 01:30:13,195] Trial 2 finished with value: 0.31431159420289856 and parameters: {'n_layers': 2, 'hidden_size': 256, 'dropout_rate': 0.2187347783754535, 'lr': 0.0008166068340329732, 'weight_decay': 0.000733133513732242, 'epochs': 46, 'batch_size': 512}. Best is trial 0 with value: 0.3201803833145434.
[I 2026-01-23 01:30:59,031] Trial 3 finished with value:

In [6]:
clf = MLPClassifier()
clf.optuna_fit(
    n_trials=20,
    X_train=sampled_train_emb,
    y_train=sampled_train_meta['target'].to_numpy(),
    X_dev=sampled_dev_emb,
    y_dev=sampled_dev_meta['target'].to_numpy(),
    train_cluster_id=sampled_train_meta['cluster_id'].to_numpy(),
    dev_cluster_id=sampled_dev_meta['cluster_id'].to_numpy()
)
print("Best trial value (lowest loss):", clf.get_best_value())

2026-01-23 01:53:49 | INFO     | audio_deepfake.MLPClassifier | Initialized model: MLPClassifier
2026-01-23 01:53:49 | INFO     | audio_deepfake.MLPClassifier | Using device: mps


(array([0., 1.], dtype=float32), array([150387,   7349])) (array([0., 1.], dtype=float32), array([15117,   720]))


2026-01-23 01:53:49 | INFO     | audio_deepfake.MLPClassifier | Using cluster_id as additional feature (train clusters: 57, dev clusters: 55)
[I 2026-01-23 01:53:49,944] A new study created in memory with name: no-name-c029e930-24db-4cb8-ba4f-8b8425092b7f


  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-01-23 01:54:17,312] Trial 0 finished with value: 0.31960461285008235 and parameters: {'n_layers': 1, 'hidden_size': 128, 'dropout_rate': 0.17220405404656222, 'lr': 0.00052387858161045, 'weight_decay': 2.338455518534999e-06, 'epochs': 14, 'batch_size': 512}. Best is trial 0 with value: 0.31960461285008235.
[I 2026-01-23 01:55:14,204] Trial 1 finished with value: 0.3543990086741016 and parameters: {'n_layers': 2, 'hidden_size': 256, 'dropout_rate': 0.14910891619285727, 'lr': 0.0032232659603336853, 'weight_decay': 4.928166781682113e-05, 'epochs': 27, 'batch_size': 512}. Best is trial 1 with value: 0.3543990086741016.
[I 2026-01-23 01:57:00,363] Trial 2 finished with value: 0.4057142857142857 and parameters: {'n_layers': 2, 'hidden_size': 192, 'dropout_rate': 0.14311907210830635, 'lr': 0.00031935991721080965, 'weight_decay': 1.2030779048071363e-06, 'epochs': 50, 'batch_size': 512}. Best is trial 2 with value: 0.4057142857142857.
[I 2026-01-23 01:58:19,114] Trial 3 finished with val