In [3]:
import numpy as np
import pandas as pd
import torch
from datasets import load_dataset, Audio
from transformers import WavLMModel, Wav2Vec2Processor

In [1]:
from datasets import load_dataset, Audio

ds = load_dataset("wqz995/AUDETER", "mls-tts-bark")
print(len(ds['dev'].cache_files))

10


In [22]:
dev = ds['dev'].cast_column('wav', Audio())
print(dev[103]['wav'].get_all_samples())

AudioSamples:
  data (shape): torch.Size([1, 343360])
  pts_seconds: 0.0
  duration_seconds: 14.306666666666667
  sample_rate: 24000



In [18]:
samples = dev[0]['wav'].get_all_samples()
for s in samples:
    print(s)
    
print(samples.sample_rate)

tensor([[0.0166, 0.0183, 0.0219,  ..., 0.0013, 0.0015, 0.0013]])
0.0
13.16
24000
24000


In [23]:
print(samples.data)

tensor([[0.0166, 0.0183, 0.0219,  ..., 0.0013, 0.0015, 0.0013]])


In [ ]:
def convert_audio_ds_into_vecs(ds, batch_size=8):
    
        
    converted_ds = {
        "keys" : [], 
        "embeddings": [],
        "durations": [],
    }
    
    for step in range(0, len(ds), batch_size):
        batch = ds[step:step + batch_size]
        
        samples_lst = [get_relevant_samples(record['wav']) for record in batch]
        

### Testing with lower version of datasets to properly work with arm architecture

In [10]:
from datasets import load_dataset, Audio

ds = load_dataset("wqz995/AUDETER", "mls-tts-bark", split="dev", streaming=True)

In [11]:
for record in ds:
    print(record)
    break

{'wav': {'path': 'dev/1055_0.wav', 'array': array([0.01663524, 0.01829608, 0.02186299, ..., 0.00131217, 0.00148168,
       0.00130851], shape=(315840,)), 'sampling_rate': 24000}, '__key__': 'dev/1055_0', '__url__': 'hf://datasets/wqz995/AUDETER@87eef4ac6eb8a6c819c3b230d6fcc176482d3a22/mls/tts/bark/dev/v0.tar'}


In [12]:
for k, v in record.items():
    print(k, v)

wav {'path': 'dev/1055_0.wav', 'array': array([0.01663524, 0.01829608, 0.02186299, ..., 0.00131217, 0.00148168,
       0.00130851], shape=(315840,)), 'sampling_rate': 24000}
__key__ dev/1055_0
__url__ hf://datasets/wqz995/AUDETER@87eef4ac6eb8a6c819c3b230d6fcc176482d3a22/mls/tts/bark/dev/v0.tar


In [6]:
wav = record['wav']
print(wav)

{'path': 'dev/1055_0.wav', 'array': array([0.01663524, 0.01829608, 0.02186299, ..., 0.00131217, 0.00148168,
       0.00130851], shape=(315840,)), 'sampling_rate': 24000}


In [9]:
print(wav['array'], type(wav['array']))
print(wav['sampling_rate'])

[0.01663524 0.01829608 0.02186299 ... 0.00131217 0.00148168 0.00130851] <class 'numpy.ndarray'>
24000
